Fix for https://github.com/wso2/product-apim/issues/10434
wso2/carbon-apimgt pull request #10097
Opened 2021-03-24 11:14 UTC by dimuthnc

Fix for https://github.com/wso2/product-apim/issues/10434

2021-03-24 11:16 UTC, tharindu1st requested changes

2021-03-24 11:16 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
> +                ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(encoded);
try-resource

2021-03-24 11:28 UTC, dimuthnc commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
> +                ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(encoded);
Fixed with https://github.com/wso2/carbon-apimgt/pull/10097/commits/3b0059cd58e15c2e627e2064dfe4c24b12ab59ba

2021-03-26 03:10 UTC, tharindu1st approved these changes

2021-03-26 03:10 UTC, merged