[Streaming API] Select streaming API protocol automatically
wso2/carbon-apimgt pull request #10258
Opened 2021-04-06 15:08 UTC by senthuran16

## Purpose
Fixes https://github.com/wso2/product-apim/issues/10759

When the user selects a Streaming API type as shown in [1], the protocol will be automatically selected as shown in [2].

[1]
<img width="1268" alt="design-new-streaming-api" src="https://user-images.githubusercontent.com/24828296/113733319-f9726d80-9717-11eb-991b-ec44d0f5c4f4.png">

[2]
<img width="822" alt="Screen Shot 2021-04-06 at 8 25 17 PM" src="https://user-images.githubusercontent.com/24828296/113733012-b4e6d200-9717-11eb-91ae-6f0be3e8b519.png">

2021-04-06 17:00 UTC, tmkasun requested changes

2021-04-06 17:01 UTC, tmkasun commented on features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/APICreateRoutes.jsx
> +                <Route path='/apis/create/streamingapi/:apiType' component={APICreateStreamingAPI} />
👍  for using path params :)

2021-04-06 20:02 UTC, senthuran16 commented on features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
> +    const { match: { params } } = props;
Done via https://github.com/wso2/carbon-apimgt/pull/10258/commits/29675e450fefdab3cd21e75deec5991437d20e12

2021-04-07 05:50 UTC, tmkasun approved these changes

2021-04-07 05:51 UTC, tmkasun approved these changes

2021-04-07 05:52 UTC, tmkasun requested changes
![image](https://user-images.githubusercontent.com/3313885/113817171-87d80500-9793-11eb-80dc-d1dba138ad54.png)
There are some eslint issues , Can you please fix them

2021-04-08 11:42 UTC, tmkasun approved these changes

2021-04-08 11:42 UTC, merged