Add searching function to scope assignments
wso2/carbon-apimgt pull request #10359
Opened 2021-04-12 05:18 UTC by HeshanSudarshana

This PR,
1. Scope Assignment UI search for roles
2. Role search UI bug

Fixes https://github.com/wso2/product-apim/issues/10507, https://github.com/wso2/product-apim/issues/10538

2021-04-12 05:33 UTC, uvindra approved these changes

2021-04-12 13:28 UTC, tmkasun approved these changes

2021-04-12 13:29 UTC, tmkasun requested changes
![image](https://user-images.githubusercontent.com/3313885/114402146-2cf24380-9bc1-11eb-902d-046d2ca55c27.png)

Please fix the linting issues

2021-04-16 17:49 UTC, tmkasun approved these changes

2021-10-01 08:09 UTC, HeshanSudarshana commented
Sent with https://github.com/wso2/apim-apps/pull/75

2021-10-01 08:09 UTC, closed without merging