get/post API revision deployment info
wso2/carbon-apimgt pull request #10683
Opened 2021-07-19 03:54 UTC by AmaliMatharaarachchi

Fixes wso2-enterprise/choreo#5075

2021-07-19 16:32 UTC, tharindu1st requested changes

2021-07-19 16:32 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +        try (Connection connection = APIMgtDBUtil.getConnection()) {
check condition to deployedAPIRevisionList ! empty to avoid connection creation

2021-07-19 16:32 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +                PreparedStatement statement = connection
need to have try resource

2021-07-19 16:32 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +//    /**
remove commented code

2021-07-19 16:32 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +                PreparedStatement statement = connection
need to handle preparedStatement try resource

2021-07-21 05:21 UTC, tharindu1st approved these changes

2021-07-21 05:25 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> +                "GROUP BY t3.NAME, t3.REVISION_UUID, t3.VHOST)";
Shall we use first charactors of the table rather than using t1, t2.. ?
eg: AM_DEPLOYED_REVISION -> DR

2021-07-21 05:31 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
> +      apiID:
```suggestion
      apiId:
```

2021-07-21 05:31 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
> +      revisionID:
```suggestion
      revisionId:
```

2021-07-22 03:39 UTC, malinthaprasan approved these changes

2021-07-22 05:10 UTC, merged