Improve certificate parsing when client cert received in header
wso2/carbon-apimgt pull request #10696
Opened 2021-07-22 08:13 UTC by VimukthiRajapaksha

This PR will remove illegal base64 characters before parsing the client certificate from request headers.

2021-07-22 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=10696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=10696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/carbon-apimgt?pullRequest=10696) it.</sub>

2021-08-04 04:22 UTC, isharac requested changes

2021-08-04 04:22 UTC, isharac commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
> +                        log.debug("Certificate in Header didn't exist in truststore");
please improve the debug log

2021-08-04 07:00 UTC, VimukthiRajapaksha commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
> +                        log.debug("Certificate in Header didn't exist in truststore");
Fixed this

2021-08-04 08:52 UTC, isharac submitted a review, later dismissed

2023-03-01 11:05 UTC, rmsamitha commented
Closing since the PR is open for more than 2 years. Please reopen if the issue still remains an PR is valid.

2023-03-01 11:05 UTC, closed without merging