Support environment specific api property
wso2/carbon-apimgt pull request #10872
Opened 2021-11-02 08:58 UTC by ruks

- Support environment-specific API property
- Support REST API to add/update properties
- Adding environment-specific properties in the runtime artifacts
- Fixes https://github.com/wso2-enterprise/choreo/issues/8981
- Fixes https://github.com/wso2-enterprise/choreo/issues/8982

2021-11-04 13:08 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +                type: string
remove

2021-11-04 13:09 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +                type: string
remove

2021-11-04 13:10 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +                type: string
remove

2021-11-04 13:10 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +        - $ref: '#/components/parameters/If-Match'
remove

2021-11-04 13:10 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +        - $ref: '#/components/parameters/If-Match'
remove

2021-11-04 13:10 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +        This operation can be used to add environment specific api properties to an existing API.
```suggestion
        This operation can be used to retrieve environment specific api properties to an existing API.
```

2021-11-04 13:11 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +        This operation can be used to update the environment specific api properties of an existing API.
```suggestion
        This operation can be used to update the environment specific API properties of an existing API.
```

2021-11-04 13:11 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +      summary: Update environment specific api properties
```suggestion
      summary: Update environment specific API properties
```

2021-11-04 13:11 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +          $ref: '#/components/responses/PreconditionFailed'
remove

2021-11-04 13:11 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> +          $ref: '#/components/responses/PreconditionFailed'
remove

2021-11-04 13:53 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                        + "        AM_API.API_UUID IN (" + apiIds + ")"
I think we cannot substitute directly as there is a possibility of SQL injections.. Shall we use something like this https://github.com/wso2/carbon-apimgt/blob/389ae2d1ab81a1b4122d73b204d743dae00d9eaf/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java#L5236-L5237

2021-11-04 13:56 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                + " WHERE AM_API_ENVIRONMENT_KEYS.ENVIRONMENT_ID IN (" + envIds + ") AND"
same as above

2021-11-04 13:56 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +        return "SELECT AM_API_ENVIRONMENT_KEYS.ENVIRONMENT_ID ENV_ID,"
shall we move all SQL queries to a seperate constants file?

2021-11-04 13:57 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +
Shall we move them to a constants file?

2021-11-04 13:57 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +            conn = APIMgtDBUtil.getConnection();
shall we use try with resources for connections too?

2021-11-04 13:58 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +            conn = APIMgtDBUtil.getConnection();
same as above, shall we fix other places too?

2021-11-04 14:31 UTC, malinthaprasan commented on features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/mysql.sql
> +    API_ID          INTEGER NOT NULL,
Shall we use the API_UUID itself here which is already unique so we can use it for the foreign key too.. it will simplify quering as well.

2021-11-08 05:24 UTC, malinthaprasan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
> +        if (content == null) {
Shall we do both null and empty check? eg: StringUtils.isBlank

2021-11-08 07:28 UTC, malinthaprasan approved these changes

2021-11-10 17:55 UTC, tharindu1st requested changes

2021-11-10 17:55 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                preparedStatement.setBlob(4, new ByteArrayInputStream(content.getBytes()));
use set binaryStream

2021-11-10 17:55 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                preparedStatement.setBlob(1, new ByteArrayInputStream(content.getBytes()));
same goes here

2021-11-10 17:55 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                    InputStream propertyConfigBlob = resultSet.getBinaryStream(1);
try resouse

2021-11-10 17:55 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/EnvironmentSpecificAPIPropertyDAO.java
> +                    InputStream propertyConfigBlob = resultSet.getBinaryStream(4);
same goes as above

2021-11-10 18:31 UTC, tharindu1st requested changes

2021-11-10 18:31 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
> +            env = ApiMgtDAO.getInstance().getEnvironment(tenantDomain, envId);
remove dao access from CXF layer

2021-11-11 16:32 UTC, tharindu1st approved these changes

2021-11-12 03:49 UTC, ruks commented
/azp run

2021-11-12 08:41 UTC, ruks commented
/azp run

2021-11-12 10:38 UTC, merged