Add backend support to Top down api development feature
wso2/carbon-apimgt pull request #11010
Opened 2022-02-07 02:55 UTC by chashikajw

### Purpose
As $subject, this will add the backend support to Top-down api development feature. 
This will add the following.

- Add a new endpoint type called service
- Fix update functionality in the service entry in API
- Add support to store apiId for the services in the service catalog
- Add a new role called "Internal/integration_dev" to the integration developer which has two scopes called  "apim:api_view_list" and "apim:api_view_definition"

### Fixes
- https://github.com/wso2/product-apim/issues/11918
- https://github.com/wso2/product-apim/issues/11917
- https://github.com/wso2/product-apim/issues/11915
- https://github.com/wso2/product-apim/issues/12170

## Related PRs
- https://github.com/wso2/apim-apps/pull/144

2022-02-07 13:17 UTC, vithu30 commented on features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/db2.sql
> +            API_ID VARCHAR(255),
We need to add this change to migration scripts too..

2022-02-09 18:15 UTC, tharindu1st requested changes

2022-02-09 18:15 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +                int tenantID = APIUtil.getTenantId(username);
remove usage of tenantId and use organization

2022-02-10 07:06 UTC, tharindu1st approved these changes

2022-02-10 07:14 UTC, vithu30 approved these changes

2022-02-10 08:51 UTC, merged