Refine client ID and Secret persistence in Solace
wso2/carbon-apimgt pull request #11088
Opened 2022-02-28 06:45 UTC by Sarangan0219

### Purpose 

Fixes,
- https://github.com/wso2/product-apim/issues/12470
- https://github.com/wso2/product-apim/issues/12469

2022-02-28 10:19 UTC, tharindu1st requested changes

2022-02-28 10:19 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +    public String getConsumerSecretFromConsumerKey(String consumerKey)throws APIManagementException {
don't retrieve consumer secret from DB call

2022-02-28 11:16 UTC, Sarangan0219 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +    public String getConsumerSecretFromConsumerKey(String consumerKey)throws APIManagementException {
Fixed https://github.com/wso2/carbon-apimgt/pull/11088/commits/a90f3eafd5548cf433628c08dd0a27e663b156b3

2022-03-01 05:42 UTC, tharindu1st approved these changes

2022-03-01 05:42 UTC, merged