added opentelemetry support
wso2/carbon-apimgt pull request #11258
Opened 2022-05-09 14:28 UTC by Rashmika998

Added OpenTelemetry support for APIM.
This pr resolves https://github.com/wso2/product-apim/issues/11816

2022-05-10 06:24 UTC, tharindu1st requested changes

2022-05-10 06:37 UTC, Rashmika998 commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencySynapseHandler.java
> +                    headers.putAll(tracerSpecificCarrier);
Extracted to the outside of if-else

2022-05-10 07:56 UTC, tharindu1st approved these changes

2022-05-11 07:31 UTC, senthuran16 approved these changes

2022-05-12 06:20 UTC, merged