Added OTLP tracer type
wso2/carbon-apimgt pull request #11355
Opened 2022-08-02 09:59 UTC by Rashmika998

## Purpose
>Added the OTLP tracing type with OpenTelemetry support for WSO2 APIM.
>This pr resolves: https://github.com/wso2/api-manager/issues/65

2022-08-02 16:06 UTC, tharindu1st requested changes

2022-08-02 16:06 UTC, tharindu1st commented on features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
> +                <{{property.name}}>{{property.value}}</{{property.name}}>
`<Property name="{{property.name}}">{{property.value}}</Property>`

2022-08-03 09:11 UTC, tharindu1st approved these changes

2022-08-03 09:18 UTC, tharindu1st requested changes

2022-08-03 09:18 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/OTLPTelemetry.java
> +        if (endPointURL != null && headerValue != null) {
use StringUtils

2022-08-03 09:22 UTC, Rashmika998 commented on components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/OTLPTelemetry.java
> +        if (endPointURL != null && headerValue != null) {
Added and resolved.

2022-08-03 09:28 UTC, tharindu1st requested changes

2022-08-03 09:28 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/OTLPTelemetry.java
> +import org.hsqldb.lib.StringUtil;
invalid import use commons.lang3

2022-08-03 09:32 UTC, Rashmika998 commented on components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/OTLPTelemetry.java
> +import org.hsqldb.lib.StringUtil;
Noted.

2022-08-03 09:45 UTC, tharindu1st approved these changes

2022-08-03 16:32 UTC, merged