Sonar cloud issues 3
wso2/carbon-apimgt pull request #11399
Opened 2022-08-21 08:28 UTC by prasa7

2022-08-22 10:02 UTC, tharindu1st requested changes

2022-08-22 10:02 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
> +                productState = null;
no need else

2022-08-22 10:02 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
> +            String productState;
String productState = null;

2022-09-03 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=11399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=11399) before we can accept your contribution.<br/>**7** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: shnrndk<br/>:white_check_mark: wasuradananjith<br/>:white_check_mark: IsuruBoyagane15<br/>:white_check_mark: ashera96<br/>:white_check_mark: IsuruMaduranga<br/>:white_check_mark: prasa7<br/>:white_check_mark: BLasan<br/>:x: wso2-jenkins-bot<br/>:x: chameerar<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/carbon-apimgt?pullRequest=11399) it.</sub>

2022-10-17 11:01 UTC, chamilaadhi commented
@prasa7 @tharindu1st shall we get this merged?

2022-11-23 04:18 UTC, prasa7 commented
Closing the PR until the PR conflicts are fixed.

2022-11-23 04:18 UTC, closed without merging