Creating Revocation Flow for JWT One Time Token feature
wso2/carbon-apimgt pull request #11398
Opened 2022-08-19 10:58 UTC by GihanAyesh

### Purpose
Fixes https://github.com/wso2/api-manager/issues/254

The [Design Documentation](https://docs.google.com/document/d/1gfhI9ozfHf8qV4SWRKfeUWFW8kSs0zAV2XFPnXGGiI0/edit?usp=sharing)

Please do not merge without the approval of @tharindu1st @HiranyaKavishani

2022-08-24 16:51 UTC, tharindu1st requested changes

2022-08-24 16:51 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediator.java
> +public class OneTimeTokenRevocationMediator extends AbstractMediator {
Override the **isContentAware** method and return false to not to build payload
   public boolean isContentAware() {
        return false;
    }

2022-08-24 16:51 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
> +    public static SignedJWTInfo getSignedJwt(String accessToken) throws ParseException {
we can revert this change due to no usage of having public

2022-08-25 08:56 UTC, tharindu1st approved these changes

2022-08-25 08:56 UTC, merged

2022-09-05 06:02 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediatorTest.java
> +}
Please add a new line for EOF

2022-09-05 06:02 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/RevokeClient.java
> +}
please add a new line for EOF

2022-09-05 06:19 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediatorTest.java
> +                getConsumerKey();
Move the code line to L151

2022-09-05 06:20 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediatorTest.java
> +        Mockito.verify(authContext,Mockito.times(0)).
Move the code line to L151 as it doesn't exceed the max length

2022-09-05 06:20 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediatorTest.java
> +                getConsumerKey();
Move the code line to L151 as it doesn't exceed the max length

2022-09-05 06:20 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediatorTest.java
> +        Mockito.verify(authContext,Mockito.times(0)).
Move the code line to L151 as it doesn't exceed the max length

2022-09-05 07:46 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/OneTimeTokenRevocationMediator.java
> +            if (StringUtils.isNotEmpty(issuer)) {
What happens issuer is an empty string with spaces