[APK] Refactor service impls
wso2/carbon-apimgt pull request #11435
Opened 2022-09-05 09:23 UTC by RakhithaRR

This PR refactors the code in following service impls.

- ApiCategoriesApiServiceImpl
- ApiProductsApiServiceImpl
- ApisApiServiceImpl
- EndpointCertificatesApiServiceImpl
- ExternalStoresApiServiceImpl
- KeyManagersApiServiceImpl
- MeApiServiceImpl
- OperationPoliciesApiServiceImpl

2022-09-05 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=11435) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=11435) before we can accept your contribution.<br/>**5** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: IsuruMaduranga<br/>:white_check_mark: binodmx<br/>:white_check_mark: tharindu1st<br/>:white_check_mark: chamilaadhi<br/>:white_check_mark: RakhithaRR<br/>:x: chameerar<br/>:x: wso2-jenkins-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/carbon-apimgt?pullRequest=11435) it.</sub>

2022-09-06 03:11 UTC, tharindu1st requested changes

2022-09-06 03:11 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/dto/APIEndpointValidationDTO.java
> +package org.wso2.carbon.apimgt.api.dto;
license header

2022-09-06 03:11 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +public class CommonUtils {
class comment

2022-09-06 03:11 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +
license

2022-09-06 03:11 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +    public static void validateScopes(API api, APIProvider apiProvider, String username) throws APIManagementException {
method commend

2022-09-06 05:43 UTC, RakhithaRR commented on components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/dto/APIEndpointValidationDTO.java
> +package org.wso2.carbon.apimgt.api.dto;
Updated with https://github.com/wso2/carbon-apimgt/pull/11435/commits/2ca8fb65474e6e00dc257b51c8444c5067239cb6

2022-09-06 05:43 UTC, RakhithaRR commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +public class CommonUtils {
Updated with https://github.com/wso2/carbon-apimgt/pull/11435/commits/2ca8fb65474e6e00dc257b51c8444c5067239cb6

2022-09-06 05:43 UTC, RakhithaRR commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +
Updated with https://github.com/wso2/carbon-apimgt/pull/11435/commits/2ca8fb65474e6e00dc257b51c8444c5067239cb6

2022-09-06 05:43 UTC, RakhithaRR commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/CommonUtils.java
> +    public static void validateScopes(API api, APIProvider apiProvider, String username) throws APIManagementException {
Updated with https://github.com/wso2/carbon-apimgt/pull/11435/commits/2ca8fb65474e6e00dc257b51c8444c5067239cb6

2022-09-07 08:01 UTC, tharindu1st approved these changes

2022-09-07 08:04 UTC, merged