Add the support to generate SOAP to REST operation elements in order
wso2/carbon-apimgt pull request #11871
Opened 2023-02-17 10:33 UTC by lakshithagunasekara

n the current SOAP to REST API creation, the SOAP envelop elements are not mapped in the same order
defined in the wsdl. The current implementation used JSONObjects to record the parameters and this will not preserve the order. However, if the operation has sequence elements, the changed order will break the operation. Instead of JSONObject, this implementation uses the swagger example data type which internally uses Linked Hash maps.

Resolves: https://github.com/wso2/api-manager/issues/1441

2023-02-17 17:20 UTC, rmsamitha requested changes
Please check the PR check test failures before merging:
- org.wso2.am.integration.tests.other.SoapToRestTestCase.testValidateInOutSequence

2023-02-21 12:42 UTC, lakshithagunasekara commented
This test failure is expected and i will send a PR with fixes for the test.

2023-02-21 13:56 UTC, lakshithagunasekara commented
Test changes https://github.com/wso2/product-apim/pull/13153

2023-02-23 06:09 UTC, rmsamitha approved these changes

2023-02-23 06:09 UTC, merged