[Feature] APIM Portal Notifications
wso2/carbon-apimgt pull request #12438
Opened 2024-05-02 07:14 UTC by HelaniUdara

2024-05-02 07:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=12438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=12438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/carbon-apimgt?pullRequest=12438) it.</sub>

2024-05-03 05:00 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +                    if (application.getGroupId() == null || application.getGroupId().isEmpty()) {
can merge together into one

2024-05-03 05:02 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/PortalNotificationDAO.java
> +            if (!comment.equals("APPROVED")) {
Swap the condition

2024-05-03 05:02 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/PortalNotificationDAO.java
> +    public int getUnreadNotificationCount(String username, String organization, String portalToDisplay, Connection conn)
check line length

2024-05-03 05:02 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> +
remove extra lines

2024-05-03 05:03 UTC, HiranyaKavishani commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/portalNotifications/WorkflowNotificationServiceImpl.java
> +            portalNotificationMetaData.setApiContext(workflowDTO.getMetadata(APIConstants.PortalNotifications.API_CONTEXT_META));
check line length

2024-06-12 04:22 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/NotificationDAO.java
> +                handleException("Failed to delete notification by id", e);
Add notification id and other context information to the log messages.

2024-06-12 04:24 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/systemNotifications/APIStateChangeWFNotifier.java
> +
Remove this blank line

2024-06-12 04:25 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/systemNotifications/AbstractWFNotifier.java
> +            APIUtil.handleException("Error while getting API usage by API ID - getAPIUsageByAPIId()", e);
Add API ID as the context information for the message. Check all the messages and add context information.

2024-06-12 04:26 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/systemNotifications/AbstractWFNotifier.java
> +            APIIdentifier apiIdEmailReplaced = new APIIdentifier(APIUtil.replaceEmailDomain(provider), apiName,
@tharindu1st Are we using APIIdentifers ?

2024-06-12 04:27 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/systemNotifications/SubscriptionUpdateWFNotifier.java
> +
Remove the blank line

2024-06-12 04:44 UTC, prasa7 commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/NotificationDAO.java
> +import java.sql.*;
Remove * imports

2024-06-12 04:44 UTC, prasa7 requested changes
Address the added comments

2025-06-19 15:29 UTC, tgtshanika commented
Closing due to inactivity.

2025-06-19 15:29 UTC, closed without merging