Add implementation for GW visibility control feature
wso2/carbon-apimgt pull request #12722
Opened 2024-12-10 12:17 UTC by npamudika

This PR adds implementation for the GW visibility control feature.

To set the visibility, use the following config in the deployment.toml. You need to provide visibility roles as an array as below.

```
[[apim.gateway.environment]]
name = "gateway-1"
type = "hybrid"
visibility = ["role-1","role-2","role-3"]
gateway_type = "Regular"
provider = "wso2"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "[https://localhost:${mgt.transport.https.port}/services/](https://localhost:$%7Bmgt.transport.https.port%7D/services/)"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "[http://localhost:${http.nio.port}](http://localhost:$%7Bhttp.nio.port%7D/)"
https_endpoint = "[https://localhost:${https.nio.port}](https://localhost:$%7Bhttps.nio.port%7D/)"
websub_event_receiver_http_endpoint = "http://localhost:9021/"
websub_event_receiver_https_endpoint = "https://localhost:8021/"
```

2024-12-10 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=12722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/carbon-apimgt?pullRequest=12722) before we can accept your contribution.<br/><hr/>**Naduni Pamudika** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/carbon-apimgt?pullRequest=12722) it.</sub>

2024-12-10 12:20 UTC, npamudika commented
This PR is related to https://github.com/wso2/api-manager/issues/3378

2025-01-24 06:40 UTC, AnuGayan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/publisher/ApisApiServiceImplUtils.java
> +        return mapApiRevisionDeployment(revisionId, vhost, displayOnDevportal, environment, environments.get(environment).getVisibility(), environments.get(environment).getPermissions().getPermission
This is longer than 120, shall we fix it,

2025-01-24 06:41 UTC, AnuGayan commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +    private String GatewayAccessPublic = "PUBLIC";
Can't we use the Constant defined before for this, Since this is kind of a duplication of a variable

2025-01-24 07:37 UTC, npamudika commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/publisher/ApisApiServiceImplUtils.java
> +        return mapApiRevisionDeployment(revisionId, vhost, displayOnDevportal, environment, environments.get(environment).getVisibility(), environments.get(environment).getPermissions().getPermission
Done

2025-01-24 07:37 UTC, npamudika commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> +    private String GatewayAccessPublic = "PUBLIC";
Fixed.

2025-01-24 09:19 UTC, tharindu1st requested changes

2025-01-24 09:19 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIRevisionDeployment.java
> +    private String visibility;
This doesn't need to be there lets retrieve from environments

2025-01-24 13:28 UTC, tharindu1st approved these changes

2025-01-24 17:27 UTC, merged