Fix NPE when adding scopes with no roles for Oracle
wso2/carbon-apimgt pull request #9252
Opened 2020-08-28 11:56 UTC by dushaniw

Fix https://github.com/wso2/product-apim/issues/9091

2020-08-30 10:15 UTC, tharindu1st requested changes

2020-08-30 10:15 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
> +        if (StringUtils.isNotBlank(scope.getRoles()) && scope.getRoles().split(",").length > 0) {
scopes.getroles.trim

2020-08-31 04:15 UTC, dushaniw commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
> +        if (StringUtils.isNotBlank(scope.getRoles()) && scope.getRoles().split(",").length > 0) {
fixed with https://github.com/wso2/carbon-apimgt/pull/9252/commits/0f1ac9c25ba76be8255ca335cb6e02b38c6f688b

2020-09-02 07:10 UTC, tharindu1st approved these changes

2020-09-04 09:41 UTC, merged