add preserve credential support to export api
wso2/carbon-apimgt pull request #9458
Opened 2020-12-02 07:23 UTC by tharindu1st

2020-12-02 07:35 UTC, dushaniw approved these changes

2020-12-03 02:01 UTC, isharac requested changes

2020-12-03 02:01 UTC, isharac commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
> +                                        Boolean preserveStatus,boolean preserveDocs,boolean preserveCredentials)
a space required.

2020-12-03 04:42 UTC, uvindra submitted a review, later dismissed

2020-12-03 04:42 UTC, uvindra commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
> +                            true, false);
preserveCredentials should be *true*

2020-12-03 04:42 UTC, uvindra commented on components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
> +                    .exportAPI(apiId, name, version, providerName, preserveStatus, exportFormat, true, false);
preserveCredentials should be *true*

2020-12-12 22:31 UTC, isharac approved these changes

2020-12-15 05:24 UTC, merged