Fixing mssql script related issues
wso2/carbon-apimgt pull request #9888
Opened 2021-02-22 10:03 UTC by CrowleyRajapakse

## Issue

Unable to execute mssql script

2021-02-23 04:48 UTC, isharac approved these changes

2021-02-23 07:18 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
> +                    Blob artifactBlob = resultSet.getBlob("ARTIFACT");
This will break for other databases.

2021-02-23 07:21 UTC, tharindu1st requested changes

2021-02-23 07:21 UTC, tharindu1st commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
> +                    Blob artifactBlob = resultSet.getBlob("ARTIFACT");
this will go here as well

2021-02-23 08:20 UTC, CrowleyRajapakse commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
> +                    Blob artifactBlob = resultSet.getBlob("ARTIFACT");
resolved

2021-02-23 08:20 UTC, CrowleyRajapakse commented on components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
> +                    Blob artifactBlob = resultSet.getBlob("ARTIFACT");
resolved

2021-02-25 16:59 UTC, tharindu1st approved these changes

2021-02-25 17:00 UTC, merged